version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_django_app
    entrypoint: /bin/sh -c "python manage.py migrate && uvicorn fastapi_app.app:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    env_file:
      - .env.docker

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A fastapi_app.celery_config worker --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env.docker

  celery_beat:
    build: .
    container_name: celery_beat
    command: celery -A fastapi_app.celery_config beat --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env.docker

volumes:
  postgres_data:
